import type {
  CustomerKind,
  CustomerStatus,
  ProjectStage,
  QuoteKind,
  QuoteStatus,
} from "@/modules/customers";

/**
 * Données réelles du bureau d'études, reprises de `EXPORT_DEVIS_-20260901.csv`
 * (export du 1er septembre 2026 : 151 devis, 103 clients, 3 775 662 € HT).
 *
 * Ce fichier est **généré** à partir de l'export, pas écrit à la main. Le seul
 * travail de transformation est celui que l'export impose :
 *
 * - **Une affaire par devis.** L'export n'a pas de notion de chantier
 *   partagé : le « nom du chantier » est une colonne du devis. Deux devis pour
 *   le même chantier — les variantes « Solution 1 / 2 / 3 » par exemple —
 *   apparaissent donc comme deux affaires. Les regrouper demanderait un
 *   rapprochement flou sur du texte libre, qui inventerait des liens que la
 *   source n'affirme pas.
 * - **Le statut devient une étape.** `etude` = devis envoyé, en attente de
 *   décision ; `accepte` = affaire gagnée ; `facture` = affaire réalisée. Le
 *   statut d'origine est conservé dans `sourceStatus` et affiché tel quel.
 * - **Le type de client est déduit du nom** (copropriété, syndic, SDC →
 *   syndic ; cabinet, SAS, SCI, immobilier → société ; sinon particulier).
 *   L'export ne le porte pas : c'est une inférence, pas une donnée.
 * - **31 devis n'ont pas de nom de client**, seulement un identifiant. Ils
 *   sont regroupés sous « Client <id> » et marqués `named: false`.
 *
 * Ce que l'export **ne contient pas**, et qu'aucun écran ne doit donc
 * prétendre connaître : l'origine de la demande, le responsable de l'affaire,
 * l'historique des relances, l'état des règlements, la ville du chantier.
 *
 * Les dates sont absolues et non relatives : ce sont de vraies dates de devis,
 * elles doivent vieillir.
 */

export type SeedQuote = {
  ref: string;
  kind: QuoteKind;
  /** Statut brut de l'export, affiché sans traduction. */
  sourceStatus: "etude" | "accepte" | "facture";
  status: QuoteStatus;
  /** Date du devis, ISO. */
  date: string;
  ht: number;
  ttc: number;
  /** Taux de TVA appliqués, en pourcentage. Deux quand le devis est mixte. */
  vat: number[];
};

export type SeedProject = {
  label: string;
  stage: ProjectStage;
  quote: SeedQuote;
};

export type SeedCustomer = {
  /** Identifiant client de l'export — la seule clé stable. */
  id: string;
  name: string;
  /** Faux quand l'export ne donnait qu'un identifiant. */
  named: boolean;
  kind: CustomerKind;
  status: CustomerStatus;
  projects: SeedProject[];
};

/** Date de l'export : les anciennetés se lisent par rapport à aujourd'hui. */
export const EXPORT_DATE = "2026-09-01";
export const EXPORT_FILE = "EXPORT_DEVIS_-20260901.csv";

export const SEED_CUSTOMERS: SeedCustomer[] = [
  {
    id: "345664",
    name: "LACQUEMENT",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une porte dans le mur porteur entre deux logements. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0144",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-09-01",
          ht: 6615.0,
          ttc: 7276.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "339152",
    name: "Le Faucheur",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création des ouvertures dans les murs porteurs. Renforcement par structures métalliques et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0145",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-09-01",
          ht: 30973.75,
          ttc: 34071.13,
          vat: [10],
        },
      },
      {
        label: "Création des ouvertures dans les murs porteurs. Renforcement par structures métalliques et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0112",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-06",
          ht: 37012.5,
          ttc: 40713.75,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "345482",
    name: "Copropriété PALAIS SELVOSA",
    named: true,
    kind: "syndic",
    status: "prospect",
    projects: [
      {
        label: "Renforcement partiel du plancher haut du garage",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0143",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-31",
          ht: 50666.5,
          ttc: 55733.15,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "266385",
    name: "Client 266385",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Réalisation d'un étaiement de mise en sécurité",
        stage: "realise",
        quote: {
          ref: "DE2026-0142",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-08-31",
          ht: 550.0,
          ttc: 605.0,
          vat: [10],
        },
      },
      {
        label: "Confortement d'un plancher",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0081",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-22",
          ht: 13708.0,
          ttc: 15078.8,
          vat: [10],
        },
      },
      {
        label: "Confortement de plancher des voutains",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0012",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-19",
          ht: 20325.0,
          ttc: 22357.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "333538",
    name: "David Haziza",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "67 bd Croisette, LOT: Plomberie",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0141",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-28",
          ht: 7944.0,
          ttc: 8738.4,
          vat: [10],
        },
      },
      {
        label: "67 bd Croisette, LOT: Electricité",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0140",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-28",
          ht: 23380.0,
          ttc: 25718.0,
          vat: [10],
        },
      },
      {
        label: "67 bd Croisette, LOT : Démolition",
        stage: "gagne",
        quote: {
          ref: "DE2026-0139",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-08-25",
          ht: 11105.25,
          ttc: 12215.78,
          vat: [10],
        },
      },
      {
        label: "Rénovation d'un appartement",
        stage: "gagne",
        quote: {
          ref: "DE2026-0097",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-07-31",
          ht: 83035.2,
          ttc: 91338.72,
          vat: [10],
        },
      },
      {
        label: "Ouverture d'un mur porteur, renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0119",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-28",
          ht: 7720.0,
          ttc: 8492.0,
          vat: [10],
        },
      },
      {
        label: "Agrandissement d'une ouverture et renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0120",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-28",
          ht: 9006.3,
          ttc: 9906.93,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "319395",
    name: "Miller",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans le mur porteur. Renforcement par structure métallique et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0076",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-26",
          ht: 5795.0,
          ttc: 6374.5,
          vat: [10],
        },
      },
      {
        label: "Démolition de cloisons semi porteuses. Renforcement par structure en plat carbone",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0077",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-16",
          ht: 6048.0,
          ttc: 6652.8,
          vat: [10],
        },
      },
      {
        label: "Réalisation de sondages structurelles",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0042",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-11",
          ht: 550.0,
          ttc: 605.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "344473",
    name: "Baud",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Travaux de reprise et de renforcement structurel / STRUCTURAL REPAIR AND STRENGTHENING WORKS",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0138",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-20",
          ht: 20590.0,
          ttc: 24708.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "344352",
    name: "Maia",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0136",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-19",
          ht: 400.0,
          ttc: 440.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "344362",
    name: "Vidal",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0137",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-19",
          ht: 11570.0,
          ttc: 12727.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "342429",
    name: "Ahmed Kazzaz",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Démolition d'un escalier. Fermeture de la trémie",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0133",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-19",
          ht: 11600.0,
          ttc: 12760.0,
          vat: [10],
        },
      },
      {
        label: "Modification de la piscine. Construction d'un local technique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0134",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-19",
          ht: 42700.0,
          ttc: 46970.0,
          vat: [10],
        },
      },
      {
        label: "Modification du poolhouse : abaissement du niveau de plancher et surélévation",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0135",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-19",
          ht: 100195.0,
          ttc: 120234.0,
          vat: [20],
        },
      },
      {
        label: "Curage de deux appartements",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0121",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-29",
          ht: 28700.0,
          ttc: 31570.0,
          vat: [10],
        },
      },
      {
        label: "Agrandissement des ouvertures de la façade, création d'une trémie d'escalier",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0122",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-29",
          ht: 58822.0,
          ttc: 64704.2,
          vat: [10],
        },
      },
      {
        label: "Création d'un plancher collaborant et autoportant",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0123",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-29",
          ht: 32034.0,
          ttc: 35237.4,
          vat: [10],
        },
      },
      {
        label: "Création d'une surélévation",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0124",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-29",
          ht: 28320.0,
          ttc: 31152.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "344215",
    name: "Dalbera",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0132",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-17",
          ht: 450.0,
          ttc: 495.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "343853",
    name: "Lozé",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Réalisation de sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0131",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-12",
          ht: 550.0,
          ttc: 605.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "343812",
    name: "Garcini",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Réalisation de sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0130",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-12",
          ht: 1200.0,
          ttc: 1320.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "305938",
    name: "Client 305938",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Réalisation de sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0129",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-07",
          ht: 1000.0,
          ttc: 1000.0,
          vat: [0],
        },
      },
      {
        label: "Réalisation de sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0063",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-01",
          ht: 7000.0,
          ttc: 7000.0,
          vat: [0],
        },
      },
      {
        label: "Sous-traitance",
        stage: "realise",
        quote: {
          ref: "DE2026-0011",
          kind: "autre",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-16",
          ht: 15000.0,
          ttc: 15000.0,
          vat: [0],
        },
      },
    ],
  },
  {
    id: "343314",
    name: "Lusso",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Démolition d'un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0128",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-06",
          ht: 5520.0,
          ttc: 6072.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "343106",
    name: "Charon",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Agrandissement de porte-fenêtres. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0127",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-08-04",
          ht: 6970.0,
          ttc: 7667.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "156771",
    name: "Giusti",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Agrandissement d'une ouverture dans le mur porteur en pierre, modification de la charpente, création d'un escalier en bois et acier.",
        stage: "gagne",
        quote: {
          ref: "DE2026-0126",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-07-31",
          ht: 13631.0,
          ttc: 14994.1,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "289994",
    name: "Jennifer MARQUES",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Variant 3 : Démolition de cloisons et renforcement de plancher par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0125",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-30",
          ht: 25374.0,
          ttc: 27911.4,
          vat: [10],
        },
      },
      {
        label: "Renforcement 2",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0115",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-16",
          ht: 41847.0,
          ttc: 46031.7,
          vat: [10],
        },
      },
      {
        label: "Démolition des cloisons. Renforcement de plancher bois par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0111",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-07-16",
          ht: 25374.0,
          ttc: 27911.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "337696",
    name: "Urso",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Reconstruction d'un local technique au droit de la piscine",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0118",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-28",
          ht: 19160.0,
          ttc: 21076.0,
          vat: [10],
        },
      },
      {
        label: "Agrandissement d'une baie vitrée. Création d'une porte dans un mur porteur. Renforcement par structure métallique et BA",
        stage: "realise",
        quote: {
          ref: "DE2026-0106",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-06-25",
          ht: 6181.82,
          ttc: 6800.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "338658",
    name: "Deroche",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Création d'ouvertures dans les murs porteurs. Renforcement par structures métalliques et poteaux en BA",
        stage: "realise",
        quote: {
          ref: "DE2026-0117",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-07-27",
          ht: 1155.0,
          ttc: 1270.5,
          vat: [10],
        },
      },
      {
        label: "Création d'ouvertures dans les murs porteurs. Renforcement par structures métalliques et poteaux en BA",
        stage: "realise",
        quote: {
          ref: "DE2026-0109",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-07-05",
          ht: 13636.36,
          ttc: 15000.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "307249",
    name: "Svetlana Anisimova",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement de plancher",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0116",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-22",
          ht: 121886.6,
          ttc: 134075.26,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "326071",
    name: "Malnou",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0082",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-17",
          ht: 4427.75,
          ttc: 4870.53,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "333667",
    name: "Client 333667",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Création d'une structure métallique pour le ballon ECS",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0099",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-10",
          ht: 14279.0,
          ttc: 14279.0,
          vat: [0],
        },
      },
      {
        label: "Modification de la piscine : création d'une structure en BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0100",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-09",
          ht: 17780.0,
          ttc: 17780.0,
          vat: [0],
        },
      },
    ],
  },
  {
    id: "339744",
    name: "Cordier",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Réalisation de sondages structurelles",
        stage: "realise",
        quote: {
          ref: "DE2026-0114",
          kind: "sondages",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-07-10",
          ht: 600.0,
          ttc: 660.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "339615",
    name: "RAMBONIMANANA",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Démolition de murs porteurs. Renforcement par structure métallique et en BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0113",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-10",
          ht: 12701.5,
          ttc: 13971.65,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "339264",
    name: "DEQUAIRE",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Reprise de plancher par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0108",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-06",
          ht: 52658.0,
          ttc: 57923.8,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "338721",
    name: "Desplanques",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création de 2 ouvertures dans un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0110",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-07-02",
          ht: 3816.0,
          ttc: 4197.6,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "338132",
    name: "Client 338132",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Appel de loyer: 2ème trimestre 2026",
        stage: "realise",
        quote: {
          ref: "DE2026-0107",
          kind: "autre",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-06-29",
          ht: 750.0,
          ttc: 900.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "324851",
    name: "MARGUET",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Suppression partielle d?une cloison semi-porteuse. Renfoncement par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0072",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-06-23",
          ht: 4090.91,
          ttc: 4500.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "335545",
    name: "Brams",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans le mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0105",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-23",
          ht: 5217.0,
          ttc: 5738.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "335387",
    name: "Client 335387",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Sondage du plancher",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0104",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-22",
          ht: 3300.0,
          ttc: 3960.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "334782",
    name: "Wasiack",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Reprise de garde de corps du balcon",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0103",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-17",
          ht: 8372.84,
          ttc: 9210.12,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "333735",
    name: "Client 333735",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Création de mezzanines métalliques auto-portées sur mesure",
        stage: "gagne",
        quote: {
          ref: "DE2026-0102",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-06-10",
          ht: 31722.0,
          ttc: 38066.4,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "333659",
    name: "Client 333659",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Renforcement du plancher sur commerces : Réalisation de sondages destructifs",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0098",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-09",
          ht: 2000.0,
          ttc: 2200.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "333271",
    name: "Souheil Benmansour",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Rénovation appartement 3 pièces",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0095",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-05",
          ht: 91731.32,
          ttc: 100904.45,
          vat: [10],
        },
      },
      {
        label: "Rénovation d'un appartement de 3 pièces",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0096",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-05",
          ht: 65710.0,
          ttc: 72281.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "332908",
    name: "Meilhac",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Agrandissement des fenêtres existantes. Démolition d'une cloison semi-porteuse. Renforcement par structures métalliques",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0094",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-03",
          ht: 9437.0,
          ttc: 10380.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "332889",
    name: "Cochin",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement d'un pilier fissuré en béton armé",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0092",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-03",
          ht: 8050.0,
          ttc: 8975.0,
          vat: [10, 20],
        },
      },
      {
        label: "Stabilisation du mur extérieur fissuré par agrafage",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0093",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-06-03",
          ht: 1550.0,
          ttc: 1705.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "332081",
    name: "Balmain",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métallique et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0091",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-28",
          ht: 5307.0,
          ttc: 5837.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "331842",
    name: "Granzow",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Renforcement de la trémie (accès cave) par plat carbone",
        stage: "realise",
        quote: {
          ref: "DE2026-0090",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-05-27",
          ht: 4885.0,
          ttc: 5373.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "299284",
    name: "Marafioti",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement de plancher haut du VS par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2025-0600",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-27",
          ht: 30692.0,
          ttc: 33761.2,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "330768",
    name: "Chantre",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Agrandissement d'une ouverture dans un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0089",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-21",
          ht: 9072.0,
          ttc: 9979.2,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "311206",
    name: "Client 311206",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Agrandissement d'ouvertures dans un mur de façade. Renforcement par structure métallique. Création des poteaux BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0088",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-20",
          ht: 20085.0,
          ttc: 22273.5,
          vat: [10, 20],
        },
      },
      {
        label: "Rénovation de l'appartement 120 bd de la Croisette",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0071",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-13",
          ht: 306528.0,
          ttc: 337180.8,
          vat: [10],
        },
      },
      {
        label: "Rénovation de l'appartement réf Tassigny",
        stage: "gagne",
        quote: {
          ref: "DE2026-0049",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-03-18",
          ht: 91731.32,
          ttc: 100904.45,
          vat: [10],
        },
      },
      {
        label: "Réhabilitation d'une villa : Travaux supplementaires",
        stage: "gagne",
        quote: {
          ref: "DE2026-0045",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-03-13",
          ht: 376250.0,
          ttc: 413875.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "212165",
    name: "Krieger",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Ouverture de murs porteurs. Renforcement par structures métalliques et BA. Construction d'une extension",
        stage: "realise",
        quote: {
          ref: "DE2026-0085",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-05-20",
          ht: 23125.0,
          ttc: 25437.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "189804",
    name: "Client 189804",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Renforcement de plancher bois",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0087",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-18",
          ht: 7791.0,
          ttc: 8570.1,
          vat: [10],
        },
      },
      {
        label: "Etaiement de mise en sécurité",
        stage: "realise",
        quote: {
          ref: "DE2026-0046",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-13",
          ht: 1800.0,
          ttc: 1980.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "329063",
    name: "Coudert",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une trémie d'escalier. Renfoncement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0086",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-05-12",
          ht: 8858.0,
          ttc: 9743.8,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "326618",
    name: "Lejeune",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renfoncement de plancher bois par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0084",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-27",
          ht: 22499.0,
          ttc: 24748.9,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "326176",
    name: "Sousan",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0083",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-23",
          ht: 6392.5,
          ttc: 7031.75,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "323129",
    name: "EA SOLA",
    named: true,
    kind: "societe",
    status: "prospect",
    projects: [
      {
        label: "Création d'un passage dans un mur porteur en pierre. Renforcement par structure en acier et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0064",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-21",
          ht: 10262.5,
          ttc: 11288.75,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "325248",
    name: "Ciolfi",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Divers travaux de repise en sous-oeuvres",
        stage: "realise",
        quote: {
          ref: "DE2026-0078",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-04-17",
          ht: 15764.4,
          ttc: 17340.84,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "320715",
    name: "Guémart",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métallique et poteaux BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0051",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-17",
          ht: 4993.5,
          ttc: 5492.85,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "289044",
    name: "Client 289044",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Mise en sécurité du balcon",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0080",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-17",
          ht: 5200.0,
          ttc: 5720.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "321254",
    name: "THEUWISSEN",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "S1 : Création d'un trémie d'escalier. Renforcement par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0055",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-04-17",
          ht: 10716.0,
          ttc: 11787.6,
          vat: [10],
        },
      },
      {
        label: "S2: Création d'un trémie d'escalier. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0056",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-23",
          ht: 11070.0,
          ttc: 12177.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "325408",
    name: "Coste",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Travaux structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0079",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-17",
          ht: 6453.0,
          ttc: 7098.3,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "220656",
    name: "COMFOURCOMMERCE",
    named: true,
    kind: "societe",
    status: "client",
    projects: [
      {
        label: "Appel de loyer: 1er trimestre 2026",
        stage: "realise",
        quote: {
          ref: "DE2026-0074",
          kind: "autre",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-04-15",
          ht: 750.0,
          ttc: 900.0,
          vat: [20],
        },
      },
      {
        label: "Appel de loyer 4ème trimestre 2025",
        stage: "realise",
        quote: {
          ref: "DE2026-0017",
          kind: "autre",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-22",
          ht: 750.0,
          ttc: 900.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "324944",
    name: "RIVIECCIO",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Suppression de la gaine de cheminée, renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0073",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-15",
          ht: 7979.0,
          ttc: 8776.9,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "325112",
    name: "Groslambert",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une mezzanine sur mesure",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0075",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-15",
          ht: 6681.5,
          ttc: 7349.65,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "295543",
    name: "Chaisaz",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Démolition d'un allège d'un ouverture existante",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0070",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-13",
          ht: 3390.0,
          ttc: 3729.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "323918",
    name: "Florence MITHAT",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Agrandissement d'une ouverture dans un mur porteur. Renforcement par structure métallique et poteaux BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0065",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-08",
          ht: 8158.0,
          ttc: 8973.8,
          vat: [10],
        },
      },
      {
        label: "Réfection d'un plancher : création d'un plancher collaborant",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0066",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-08",
          ht: 57189.0,
          ttc: 62907.9,
          vat: [10],
        },
      },
      {
        label: "Etudes structurelles",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0067",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-08",
          ht: 4200.0,
          ttc: 5040.0,
          vat: [20],
        },
      },
      {
        label: "Abaissement du plancher bas R-1. Reprise des fondations",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0069",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-04-08",
          ht: 156250.0,
          ttc: 171875.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "289171",
    name: "Jean KOJA",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Travaux supplémentaires renfoncement",
        stage: "realise",
        quote: {
          ref: "DE2026-0068",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-04-08",
          ht: 2272.73,
          ttc: 2500.0,
          vat: [10],
        },
      },
      {
        label: "Agrandissement des ouvertures 2",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0062",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-30",
          ht: 16407.0,
          ttc: 18047.7,
          vat: [10],
        },
      },
      {
        label: "Agrandissement des ouvertures dans les murs porteurs",
        stage: "realise",
        quote: {
          ref: "DE2026-0059",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-30",
          ht: 13205.0,
          ttc: 14525.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "316890",
    name: "Pereira",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Démolition d'un mur porteur et des cloisons. Renforcement par structure bois, acier et BA",
        stage: "gagne",
        quote: {
          ref: "DE2026-0038",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-03-30",
          ht: 10000.5,
          ttc: 11000.55,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "322031",
    name: "KUENTZ",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Réalisation de sondages",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0061",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-27",
          ht: 800.0,
          ttc: 880.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "321881",
    name: "Client 321881",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Support métallique pour store banne",
        stage: "realise",
        quote: {
          ref: "DE2026-0058",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-26",
          ht: 5100.0,
          ttc: 6120.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "261865",
    name: "Client 261865",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Création d'un plancher : phase 2",
        stage: "realise",
        quote: {
          ref: "DE2026-0057",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-25",
          ht: 7505.0,
          ttc: 9006.0,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "321211",
    name: "JOVANOVIC",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Réhabilitation et extension d'une maison. Construction d'un garage",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0054",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-23",
          ht: 422513.0,
          ttc: 507015.6,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "317972",
    name: "Rosenblatt",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Travaux supplémentaires : Réalisation de l'éclisse",
        stage: "realise",
        quote: {
          ref: "DE2026-0052",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-20",
          ht: 636.36,
          ttc: 700.0,
          vat: [10],
        },
      },
      {
        label: "Renforcement d'une poutre noyée par une structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0008",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-12",
          ht: 5864.0,
          ttc: 6450.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "209492",
    name: "Citya Nice Immobilière",
    named: true,
    kind: "societe",
    status: "client",
    projects: [
      {
        label: "Modification de plomberie",
        stage: "realise",
        quote: {
          ref: "DE2026-0053",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-20",
          ht: 1050.0,
          ttc: 1155.0,
          vat: [10],
        },
      },
      {
        label: "Confortement PH des caves",
        stage: "realise",
        quote: {
          ref: "DE2024-0233",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-29",
          ht: 13907.0,
          ttc: 16688.4,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "320412",
    name: "Zaffini",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement métallique d'un plancher de garage",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0048",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-20",
          ht: 14312.0,
          ttc: 15743.2,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "287209",
    name: "Client 287209",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Dépose des lambourdes de plancher bois",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0050",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-18",
          ht: 25070.0,
          ttc: 27577.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "302317",
    name: "Hoareau",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Avenant au devis DE2025-0622 : Création d'une trémie d'escalier",
        stage: "realise",
        quote: {
          ref: "DE2026-0047",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-16",
          ht: 587.0,
          ttc: 645.7,
          vat: [10],
        },
      },
      {
        label: "Réalisation de dallage",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0036",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-20",
          ht: 3370.0,
          ttc: 3707.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "321915",
    name: "Haitem Meftah",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Fourniture et installation d?une cuisine équipée et placards IKEA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0060",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-12",
          ht: 9150.0,
          ttc: 10065.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "319589",
    name: "Dusart",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Agrandissement des ouvertures dans le mur porteur de façade. Renforcement par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0044",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-12",
          ht: 5527.0,
          ttc: 6079.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "319406",
    name: "Garoupe Beach",
    named: true,
    kind: "societe",
    status: "prospect",
    projects: [
      {
        label: "Remplacement d'une pergola",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0043",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-11",
          ht: 16155.5,
          ttc: 17771.05,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "318966",
    name: "Client 318966",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Réalisation de sondages, installation d'une trappe",
        stage: "realise",
        quote: {
          ref: "DE2026-0041",
          kind: "sondages",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-09",
          ht: 820.0,
          ttc: 902.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "318494",
    name: "Fabry",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Réalisation de sondages structurelles",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0040",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-03-05",
          ht: 580.0,
          ttc: 638.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "317656",
    name: "Patrick Chiche",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Reprise d'une poutre en BA sectionné",
        stage: "realise",
        quote: {
          ref: "DE2026-0039",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-03-02",
          ht: 6552.0,
          ttc: 7207.2,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "157069",
    name: "Cabinet VIELLE&CIE",
    named: true,
    kind: "societe",
    status: "prospect",
    projects: [
      {
        label: "Renforcement d'un plancher par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0037",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-23",
          ht: 21564.0,
          ttc: 23720.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "315780",
    name: "SDC",
    named: true,
    kind: "syndic",
    status: "prospect",
    projects: [
      {
        label: "Réfection d'un plancher",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0035",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-17",
          ht: 41578.0,
          ttc: 45735.8,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "304214",
    name: "Gras",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métallique et en BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2025-0627",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-16",
          ht: 8834.0,
          ttc: 9717.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "313008",
    name: "Client 313008",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Modification de la charpente. Installation d'une ossature métallique. Création d'une trémie d'escalier, renfoncement de plancher.",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0026",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-13",
          ht: 34121.55,
          ttc: 37533.71,
          vat: [10],
        },
      },
      {
        label: "Renforcement de plancher",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0027",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-02",
          ht: 12250.0,
          ttc: 13475.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "161519",
    name: "Martinez",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'un trémie d'escalier. Renforcement par structure métallique.",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0034",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-12",
          ht: 8967.0,
          ttc: 9863.7,
          vat: [10],
        },
      },
      {
        label: "Création d'une trémie d'escalier. Renforcement par la structure métallique et en BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2023-0072",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-11",
          ht: 8967.0,
          ttc: 9863.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "314633",
    name: "Balland",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'ouvertures dans murs porteurs. Renforcement par structures métalliques et poteaux BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0033",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-10",
          ht: 24640.0,
          ttc: 27104.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "304377",
    name: "Bonifassi",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Agrandissement des ouvertures dans les murs porteurs. Renforcement par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2025-0628",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-02-09",
          ht: 17003.0,
          ttc: 18703.3,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "314447",
    name: "Manso",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Démolition d'un mur porteur. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0031",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-09",
          ht: 9143.0,
          ttc: 10057.3,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "314471",
    name: "Client 314471",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans un mur porteur. Renforcement par structure métalliques et raidisseurs BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0032",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-09",
          ht: 6068.5,
          ttc: 7282.2,
          vat: [20],
        },
      },
    ],
  },
  {
    id: "297233",
    name: "Lamy Cannes Syndic",
    named: true,
    kind: "syndic",
    status: "prospect",
    projects: [
      {
        label: "Mise en place étais bandeau au plafond",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0030",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-06",
          ht: 600.0,
          ttc: 660.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "308315",
    name: "Koja",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Travaux de reprise en sous-oeuvre",
        stage: "realise",
        quote: {
          ref: "DE2026-0004",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-02-05",
          ht: 23000.0,
          ttc: 25300.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "313316",
    name: "Laurent",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement des fondations suite à la terrassement",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0028",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-02",
          ht: 79568.0,
          ttc: 87524.8,
          vat: [10],
        },
      },
      {
        label: "Suppression des piliers dans le sous-sol. Renforcement de plancher. Création des ouvertures dans les murs porteurs",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0029",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-02-02",
          ht: 39767.0,
          ttc: 43743.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "300404",
    name: "Client 300404",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Reprise du plancher bois par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0001",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-02-02",
          ht: 15643.47,
          ttc: 17207.82,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "312421",
    name: "ZANCHI",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Solution 3: Création d'une ouvertures dans les mur porteur en pierre. Renforcement par structure en acier et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0025",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-30",
          ht: 7194.0,
          ttc: 7913.4,
          vat: [10],
        },
      },
      {
        label: "Solution 1: Création des ouvertures dans les murs porteurs en pierre. Renforcement par structure en acier et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0021",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-28",
          ht: 13450.0,
          ttc: 14795.0,
          vat: [10],
        },
      },
      {
        label: "Solution 2: Création des ouvertures dans les murs porteurs en pierre. Renforcement par structure en acier et BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0022",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-28",
          ht: 17793.5,
          ttc: 19572.85,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "312678",
    name: "Delattre",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Remplacement d'une structure existante par une structure métallique. Ouverture d'une fenêtre et consolidation par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0024",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-30",
          ht: 10007.0,
          ttc: 11007.7,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "305202",
    name: "Birbes",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Création d'ouvertures dans un mur porteur. Renforcement par structures métalliques",
        stage: "realise",
        quote: {
          ref: "DE2025-0633",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-30",
          ht: 5682.0,
          ttc: 6250.2,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "312673",
    name: "Guillem",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'un passage dans une cloison semi-porteuse. Renforcement par structure en acier",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0023",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-28",
          ht: 1588.0,
          ttc: 1746.8,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "304890",
    name: "Client 304890",
    named: false,
    kind: "autre",
    status: "prospect",
    projects: [
      {
        label: "Renforcement de plancher sur 4 niveaux de l'immeuble",
        stage: "devis_envoye",
        quote: {
          ref: "DE2025-0632",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-28",
          ht: 172884.0,
          ttc: 190172.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "278549",
    name: "Vicquenault",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Travaux supplémentaires",
        stage: "realise",
        quote: {
          ref: "DE2026-0020",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-28",
          ht: 1700.0,
          ttc: 1870.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "312007",
    name: "Resch",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Renforcement de plancher suite à la démolition des cloisons",
        stage: "realise",
        quote: {
          ref: "DE2026-0018",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-28",
          ht: 5455.0,
          ttc: 6000.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "312223",
    name: "Morlot",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'une ouverture dans une voile en béton armé. Renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0019",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-27",
          ht: 7976.0,
          ttc: 8773.6,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "310977",
    name: "Clavelin",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Option 2 (si mur en agglos): Suppression d'un poteau et renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0014",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-20",
          ht: 7705.0,
          ttc: 8475.5,
          vat: [10],
        },
      },
      {
        label: "Option 1 (mur en béton) : Suppression d'un poteau et renforcement par structure métallique",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0015",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-20",
          ht: 6385.0,
          ttc: 7023.5,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "303823",
    name: "Client 303823",
    named: false,
    kind: "autre",
    status: "client",
    projects: [
      {
        label: "Travaux supplémentaires : création de la dalle de renfort",
        stage: "realise",
        quote: {
          ref: "DE2026-0016",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-20",
          ht: 1640.0,
          ttc: 1804.0,
          vat: [10],
        },
      },
      {
        label: "Création d'une dalle de renfort",
        stage: "gagne",
        quote: {
          ref: "DE2026-0007",
          kind: "etude",
          sourceStatus: "accepte",
          status: "accepte",
          date: "2026-01-08",
          ht: 3750.0,
          ttc: 4125.0,
          vat: [10],
        },
      },
      {
        label: "Construction d'un mur en parpaings banchés. Construction d'un mur de soutènement en BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0005",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-07",
          ht: 20680.0,
          ttc: 22748.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "308671",
    name: "Arcelli",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Consolidation du plancher bois",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0013",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-19",
          ht: 2000.0,
          ttc: 2200.0,
          vat: [10],
        },
      },
      {
        label: "Sondages structurels",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0006",
          kind: "sondages",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-08",
          ht: 363.64,
          ttc: 400.0,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "309365",
    name: "Crousaud",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Création d'ouvertures dans murs porteurs. Renforcement par structure métallique et raidisseurs BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0010",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-13",
          ht: 12468.0,
          ttc: 13714.8,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "309159",
    name: "Abdelhafidh",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Renforcement du plancher par des plats en carbone suite à la démolition des cloisons",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0009",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-12",
          ht: 6517.5,
          ttc: 7169.25,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "308279",
    name: "ENGELS",
    named: true,
    kind: "particulier",
    status: "prospect",
    projects: [
      {
        label: "Agrandissement des ouvertures dans les murs de façade. Renforcement par structures métalliques et poteaux BA",
        stage: "devis_envoye",
        quote: {
          ref: "DE2026-0003",
          kind: "etude",
          sourceStatus: "etude",
          status: "envoye",
          date: "2026-01-06",
          ht: 14294.0,
          ttc: 15723.4,
          vat: [10],
        },
      },
    ],
  },
  {
    id: "291759",
    name: "Pallavicini",
    named: true,
    kind: "particulier",
    status: "client",
    projects: [
      {
        label: "Création d'une ouverture 315x210 dans une cloison semi-porteuse. Renforcement par structure métallique",
        stage: "realise",
        quote: {
          ref: "DE2026-0002",
          kind: "etude",
          sourceStatus: "facture",
          status: "realise",
          date: "2026-01-06",
          ht: 4713.0,
          ttc: 5184.3,
          vat: [10],
        },
      },
    ],
  },
];
